### ISSUE TITLE
Single day query yields no output

### ISSUE THREAD

**Issue by myselfhimself** [kenchan/gh-furik#4]
Hello
thank you for this extension.

The following commands (for a day where there has been activity going on), output nothing:
gh furik --from 2022-10-05 --to 2022-10-06
or
gh furik --from 2022-10-05 --to 2022-10-05

Does someone reproduce it as well?

**Comment by myselfhimself** [comment]
(background vision)
The business use case is:
for what projects have I worked on that (those) days?
for each commit in each project what where commit times?
This may help freelancers (or employees) remember more or less how many hours they have worked for which project on given dates...

**Comment by kenchan** [comment]
I'm sorry for the late reply.
Please wait while I check it.

**Comment by kenchan** [comment]
When you want to take information for one day, specify the next day in the `to` parameter.

```
gh furik --from 2022-10-05 --to 2022-10-06
```

But, the output was only what could be retrieved via GitHub's Event API. This includes pull request open/close, reviews, etc., but not commits.

Can you try again?Thanks for using it.
